// Mock Data for OCPD Insurance Platform
import {
    Client,
    Policy,
    Claim,
    QuoteRequest,
    DashboardStats,
    Vehicle,
    RiskProfile,
    PolicyClause,
} from '@/types';

// Helper to generate dates
const daysFromNow = (days: number): Date => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date;
};

const daysAgo = (days: number): Date => {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date;
};

// ============ CLIENTS ============
export const mockClients: Client[] = [
    {
        id: 'client-1',
        nip: '5213456789',
        name: 'Trans-Europa Sp. z o.o.',
        email: 'biuro@trans-europa.pl',
        phone: '+48 22 123 45 67',
        regonData: {
            nip: '5213456789',
            regon: '123456789',
            name: 'Trans-Europa Sp. z o.o.',
            shortName: 'Trans-Europa',
            address: {
                street: 'ul. Transportowa 15',
                city: 'Warszawa',
                postalCode: '02-495',
                voivodeship: 'mazowieckie',
            },
            pkdCodes: ['49.41.Z', '52.29.C'],
            registrationDate: '2010-03-15',
            employeeCount: '50-99',
            legalForm: 'Sp. z o.o.',
        },
        fleet: [],
        riskProfile: {
            overallScore: 72,
            riskLevel: 'MEDIUM',
            yearsInBusiness: 14,
            claimsRatio: 0.35,
            bonusMalus: -10,
            transportTypes: ['ADR', 'Plandeki', 'Chłodnie'],
            mainRoutes: ['POLAND', 'EUROPE'],
            hasADRCertificate: true,
            hasTAPACertificate: false,
        },
        claimsHistory: [],
        createdAt: daysAgo(365 * 3),
        updatedAt: daysAgo(30),
        brokerId: 'broker-1',
    },
    {
        id: 'client-2',
        nip: '7891234567',
        name: 'Szybki Transport Kowalski',
        email: 'jan@szybkitransport.pl',
        phone: '+48 605 111 222',
        regonData: {
            nip: '7891234567',
            regon: '987654321',
            name: 'Szybki Transport Jan Kowalski',
            address: {
                street: 'ul. Główna 5',
                city: 'Poznań',
                postalCode: '60-001',
                voivodeship: 'wielkopolskie',
            },
            pkdCodes: ['49.41.Z'],
            registrationDate: '2018-06-01',
            legalForm: 'Jednoosobowa działalność',
        },
        fleet: [],
        riskProfile: {
            overallScore: 85,
            riskLevel: 'LOW',
            yearsInBusiness: 6,
            claimsRatio: 0.15,
            bonusMalus: -20,
            transportTypes: ['Plandeki'],
            mainRoutes: ['POLAND'],
            hasADRCertificate: false,
            hasTAPACertificate: false,
        },
        claimsHistory: [],
        createdAt: daysAgo(365 * 2),
        updatedAt: daysAgo(7),
        brokerId: 'broker-1',
    },
    {
        id: 'client-3',
        nip: '1234567890',
        name: 'Logistyka Międzynarodowa SA',
        email: 'kontakt@logistyka-miedzynarodowa.pl',
        phone: '+48 12 345 67 89',
        regonData: {
            nip: '1234567890',
            regon: '111222333',
            name: 'Logistyka Międzynarodowa SA',
            address: {
                street: 'ul. Logistyczna 100',
                city: 'Kraków',
                postalCode: '30-001',
                voivodeship: 'małopolskie',
            },
            pkdCodes: ['49.41.Z', '52.21.Z', '52.29.C'],
            registrationDate: '2005-01-10',
            employeeCount: '250-499',
            legalForm: 'SA',
        },
        fleet: [],
        riskProfile: {
            overallScore: 68,
            riskLevel: 'MEDIUM',
            yearsInBusiness: 19,
            claimsRatio: 0.42,
            bonusMalus: 0,
            transportTypes: ['ADR', 'Plandeki', 'Chłodnie', 'Ciężkie'],
            mainRoutes: ['POLAND', 'EUROPE', 'WORLD'],
            hasADRCertificate: true,
            hasTAPACertificate: true,
        },
        claimsHistory: [],
        createdAt: daysAgo(365 * 5),
        updatedAt: daysAgo(2),
        brokerId: 'broker-1',
    },
    {
        id: 'client-4',
        nip: '9876543210',
        name: 'Fresh Cold Transport Sp. z o.o.',
        email: 'info@freshcold.pl',
        phone: '+48 58 999 88 77',
        regonData: {
            nip: '9876543210',
            regon: '444555666',
            name: 'Fresh Cold Transport Sp. z o.o.',
            address: {
                street: 'ul. Mroźna 22',
                city: 'Gdańsk',
                postalCode: '80-001',
                voivodeship: 'pomorskie',
            },
            pkdCodes: ['49.41.Z'],
            registrationDate: '2019-09-01',
            employeeCount: '20-49',
            legalForm: 'Sp. z o.o.',
        },
        fleet: [],
        riskProfile: {
            overallScore: 55,
            riskLevel: 'HIGH',
            yearsInBusiness: 5,
            claimsRatio: 0.65,
            bonusMalus: 15,
            transportTypes: ['Chłodnie'],
            mainRoutes: ['EUROPE'],
            hasADRCertificate: false,
            hasTAPACertificate: false,
        },
        claimsHistory: [],
        createdAt: daysAgo(365),
        updatedAt: daysAgo(14),
        brokerId: 'broker-1',
    },
];

// ============ POLICIES ============
export const mockPolicies: Policy[] = [
    {
        id: 'policy-1',
        policyNumber: 'OCPD/2024/001234',
        clientId: 'client-1',
        client: mockClients[0],
        type: 'OCPD',
        status: 'ACTIVE',
        sumInsured: 500000,
        territorialScope: 'EUROPE',
        clauses: [
            {
                id: 'clause-1',
                type: 'GROSS_NEGLIGENCE',
                name: 'Rażące niedbalstwo',
                description: 'Ochrona na wypadek szkód spowodowanych rażącym niedbalstwem',
                sublimit: 500000,
                sublimitPercentage: 100,
                premium: 1200,
                isActive: true,
            },
            {
                id: 'clause-2',
                type: 'PARKING',
                name: 'Klauzula postojowa',
                description: 'Rozszerzona ochrona na parkingach niestrzeżonych',
                sublimit: 250000,
                sublimitPercentage: 50,
                premium: 1600,
                isActive: true,
            },
        ],
        basePremium: 6000,
        clausesPremium: 2800,
        totalPremium: 8800,
        validFrom: daysAgo(180),
        validTo: daysFromNow(185),
        issuedAt: daysAgo(180),
        apkCompleted: true,
        ipidGenerated: true,
        brokerId: 'broker-1',
        createdAt: daysAgo(185),
        updatedAt: daysAgo(180),
    },
    {
        id: 'policy-2',
        policyNumber: 'OCPD/2024/001235',
        clientId: 'client-2',
        client: mockClients[1],
        type: 'OCPD',
        status: 'ACTIVE',
        sumInsured: 200000,
        territorialScope: 'POLAND',
        clauses: [
            {
                id: 'clause-3',
                type: 'GROSS_NEGLIGENCE',
                name: 'Rażące niedbalstwo',
                description: 'Ochrona na wypadek szkód spowodowanych rażącym niedbalstwem',
                sublimit: 200000,
                sublimitPercentage: 100,
                premium: 320,
                isActive: true,
            },
        ],
        basePremium: 1600,
        clausesPremium: 320,
        totalPremium: 1920,
        validFrom: daysAgo(90),
        validTo: daysFromNow(275),
        issuedAt: daysAgo(90),
        apkCompleted: true,
        ipidGenerated: true,
        brokerId: 'broker-1',
        createdAt: daysAgo(95),
        updatedAt: daysAgo(90),
    },
    {
        id: 'policy-3',
        policyNumber: 'OCPD/2024/001236',
        clientId: 'client-3',
        client: mockClients[2],
        type: 'OCPD',
        status: 'ACTIVE',
        sumInsured: 1000000,
        territorialScope: 'WORLD',
        clauses: [
            {
                id: 'clause-4',
                type: 'GROSS_NEGLIGENCE',
                name: 'Rażące niedbalstwo',
                description: 'Ochrona na wypadek szkód spowodowanych rażącym niedbalstwem',
                sublimit: 1000000,
                sublimitPercentage: 100,
                premium: 2700,
                isActive: true,
            },
            {
                id: 'clause-5',
                type: 'SUBCONTRACTORS',
                name: 'Klauzula podwykonawców',
                description: 'Ochrona na podwykonawców',
                sublimit: 1000000,
                sublimitPercentage: 100,
                premium: 3240,
                isActive: true,
            },
            {
                id: 'clause-6',
                type: 'ADR',
                name: 'Towary niebezpieczne (ADR)',
                description: 'Ochrona dla transportu ADR',
                sublimit: 500000,
                sublimitPercentage: 50,
                premium: 5400,
                isActive: true,
            },
        ],
        basePremium: 18000,
        clausesPremium: 11340,
        totalPremium: 29340,
        validFrom: daysAgo(60),
        validTo: daysFromNow(305),
        issuedAt: daysAgo(60),
        apkCompleted: true,
        ipidGenerated: true,
        brokerId: 'broker-1',
        createdAt: daysAgo(65),
        updatedAt: daysAgo(60),
    },
    {
        id: 'policy-4',
        policyNumber: 'OCPD/2024/001237',
        clientId: 'client-4',
        client: mockClients[3],
        type: 'OCPD',
        status: 'ACTIVE',
        sumInsured: 300000,
        territorialScope: 'EUROPE',
        clauses: [
            {
                id: 'clause-7',
                type: 'REFRIGERATED',
                name: 'Ładunki chłodnicze',
                description: 'Ochrona dla ładunków chłodniczych',
                sublimit: 300000,
                sublimitPercentage: 100,
                premium: 900,
                isActive: true,
            },
        ],
        basePremium: 3600,
        clausesPremium: 900,
        totalPremium: 4500,
        validFrom: daysAgo(330),
        validTo: daysFromNow(35),
        issuedAt: daysAgo(330),
        apkCompleted: true,
        ipidGenerated: true,
        brokerId: 'broker-1',
        createdAt: daysAgo(335),
        updatedAt: daysAgo(330),
    },
    {
        id: 'policy-5',
        policyNumber: 'OCPD/2023/000998',
        clientId: 'client-1',
        client: mockClients[0],
        type: 'OCPD',
        status: 'EXPIRED',
        sumInsured: 400000,
        territorialScope: 'EUROPE',
        clauses: [],
        basePremium: 4800,
        clausesPremium: 0,
        totalPremium: 4800,
        validFrom: daysAgo(545),
        validTo: daysAgo(180),
        issuedAt: daysAgo(545),
        apkCompleted: true,
        ipidGenerated: true,
        brokerId: 'broker-1',
        createdAt: daysAgo(550),
        updatedAt: daysAgo(180),
    },
];

// ============ CLAIMS ============
export const mockClaims: Claim[] = [
    {
        id: 'claim-1',
        claimNumber: 'SZK/2024/00123',
        policyId: 'policy-1',
        clientId: 'client-1',
        incidentDate: daysAgo(45),
        reportedDate: daysAgo(43),
        description: 'Uszkodzenie ładunku elektroniki podczas transportu z Niemiec. Niewłaściwe zabezpieczenie towaru na paletach.',
        location: 'A2, okolice Poznania',
        claimedAmount: 85000,
        reservedAmount: 75000,
        status: 'UNDER_REVIEW',
        documents: [],
        createdAt: daysAgo(43),
        updatedAt: daysAgo(10),
    },
    {
        id: 'claim-2',
        claimNumber: 'SZK/2024/00124',
        policyId: 'policy-3',
        clientId: 'client-3',
        incidentDate: daysAgo(20),
        reportedDate: daysAgo(18),
        description: 'Kradzież części ładunku z parkingu w Holandii. Parking niestrzeżony.',
        location: 'Rotterdam, Holandia',
        claimedAmount: 120000,
        reservedAmount: 100000,
        status: 'UNDER_REVIEW',
        documents: [],
        createdAt: daysAgo(18),
        updatedAt: daysAgo(5),
    },
    {
        id: 'claim-3',
        claimNumber: 'SZK/2024/00100',
        policyId: 'policy-4',
        clientId: 'client-4',
        incidentDate: daysAgo(90),
        reportedDate: daysAgo(88),
        description: 'Zepsucie ładunku mrożonek z powodu awarii agregatu chłodniczego.',
        location: 'Trasa Gdańsk - Monachium',
        claimedAmount: 45000,
        paidAmount: 42000,
        status: 'PAID',
        documents: [],
        createdAt: daysAgo(88),
        updatedAt: daysAgo(30),
    },
];

// ============ QUOTES ============
export const mockQuotes: QuoteRequest[] = [
    {
        id: 'quote-1',
        clientNIP: '1112223334',
        requestedSumInsured: 300000,
        requestedScope: 'EUROPE',
        requestedClauses: ['GROSS_NEGLIGENCE', 'PARKING'],
        apkData: {
            mainCargoTypes: ['Elektronika', 'AGD'],
            averageCargoValue: 80000,
            maxSingleShipmentValue: 200000,
            monthlyShipments: 25,
        },
        calculatedPremium: 5200,
        status: 'CALCULATED',
        validUntil: daysFromNow(14),
        createdAt: daysAgo(3),
        brokerId: 'broker-1',
    },
    {
        id: 'quote-2',
        clientNIP: '5556667778',
        requestedSumInsured: 150000,
        requestedScope: 'POLAND',
        requestedClauses: ['GROSS_NEGLIGENCE'],
        apkData: {
            mainCargoTypes: ['Materiały budowlane'],
            averageCargoValue: 30000,
            maxSingleShipmentValue: 100000,
            monthlyShipments: 40,
        },
        calculatedPremium: 1800,
        status: 'SENT',
        validUntil: daysFromNow(7),
        createdAt: daysAgo(7),
        brokerId: 'broker-1',
    },
    {
        id: 'quote-3',
        clientNIP: '9998887776',
        requestedSumInsured: 500000,
        requestedScope: 'EUROPE',
        requestedClauses: ['GROSS_NEGLIGENCE', 'SUBCONTRACTORS', 'REFRIGERATED'],
        apkData: {
            mainCargoTypes: ['Żywność', 'Produkty mleczne'],
            averageCargoValue: 60000,
            maxSingleShipmentValue: 150000,
            monthlyShipments: 60,
            temperatureControlled: true,
        },
        status: 'DRAFT',
        createdAt: daysAgo(1),
        brokerId: 'broker-1',
    },
];

// ============ DASHBOARD STATS ============
export const mockDashboardStats: DashboardStats = {
    activePolicies: mockPolicies.filter(p => p.status === 'ACTIVE').length,
    expiringPolicies30Days: mockPolicies.filter(p => {
        const daysToExpiry = Math.ceil((p.validTo.getTime() - Date.now()) / (1000 * 60 * 60 * 24));
        return p.status === 'ACTIVE' && daysToExpiry <= 30 && daysToExpiry > 0;
    }).length,
    expiringPolicies60Days: mockPolicies.filter(p => {
        const daysToExpiry = Math.ceil((p.validTo.getTime() - Date.now()) / (1000 * 60 * 60 * 24));
        return p.status === 'ACTIVE' && daysToExpiry <= 60 && daysToExpiry > 0;
    }).length,
    totalPremium: mockPolicies
        .filter(p => p.status === 'ACTIVE')
        .reduce((sum, p) => sum + p.totalPremium, 0),
    pendingQuotes: mockQuotes.filter(q => q.status === 'CALCULATED' || q.status === 'SENT').length,
    openClaims: mockClaims.filter(c => c.status === 'UNDER_REVIEW' || c.status === 'REPORTED').length,
    claimsRatio: 0.32,
    topClients: [
        { name: 'Logistyka Międzynarodowa SA', premium: 29340 },
        { name: 'Trans-Europa Sp. z o.o.', premium: 8800 },
        { name: 'Fresh Cold Transport', premium: 4500 },
        { name: 'Szybki Transport Kowalski', premium: 1920 },
    ],
};

// ============ PREMIUM HISTORY ============
export const mockPremiumHistory = [
    { month: 'Sty', premium: 28000, claims: 5000 },
    { month: 'Lut', premium: 32000, claims: 8000 },
    { month: 'Mar', premium: 35000, claims: 12000 },
    { month: 'Kwi', premium: 38000, claims: 6000 },
    { month: 'Maj', premium: 42000, claims: 15000 },
    { month: 'Cze', premium: 44560, claims: 42000 },
    { month: 'Lip', premium: 41000, claims: 9000 },
    { month: 'Sie', premium: 39000, claims: 7000 },
    { month: 'Wrz', premium: 43000, claims: 11000 },
    { month: 'Paź', premium: 45000, claims: 8000 },
    { month: 'Lis', premium: 47000, claims: 5000 },
    { month: 'Gru', premium: 44560, claims: 13000 },
];
